.TH CR 1
.SH NAME
cr \- create new files and directories
.SH SYNOPSIS
cr [-flags] file|directory/
.SH DESCRIPTION
A wrapper for creating new files and directories
.SH FLAGS
-v version
.br
-h help
.br
-r directory mode
.br
-n normal mode
.br
-o print output
.br
-d print output directory only
.br
-f print output file only
.br
-s silent the output
.SH USAGE
cr file
.br
cr directory/
.br
cr directory/file 
.br
cr directory/directory/
.br
cr directory/directory/file
.SH SEE ALSO
mkdir(8)
.SH AUTHOR
Noor Wachid (https://github.com/wachd)
