.TH CR 1
.SH NAME
cr \- create new files and recursive directories
.SH SYNOPSIS
cr [-flags] file|directory/
.SH DESCRIPTION
A wrapper for creating new files and directories
.SH FLAGS
-v Print out current version.
.br
-h Print out help text.
.br
-r Change to directory mode. It will create directory without trailing '/' slash.
.br
-n Go back to normal mode.
.br
-o Print the current argument given.
.br
-d Print the current directory argument given.
.br
-f Print the current file argument given.
.br
-s Silent the current argument given.
.SH USAGE
cr file
.br
cr directory/
.br
cr directory/file 
.br
cr directory/directory/
.br
cr directory/directory/file
.SH SEE ALSO
mkdir(8)
.SH AUTHOR
Noor Wachid (https://github.com/wachd)
